<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserWatchHistoriesSeeder extends Seeder
{
    public function run()
    {
        // Clear the user_watch_histories table
        \DB::table('user_watch_histories')->delete();
        
        // Insert records into the user_watch_histories table
        \DB::table('user_watch_histories')->insert([
            [
                'entertainment_id' => 101,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'movie', 
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 15,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'tvshow', 
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 35,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'movie',
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => null,

            ],
            [
                'entertainment_id' => 12,
                'user_id' => 4,
                'profile_id' => 4,
                'entertainment_type' => 'tvshow', 
                'created_by' => 4,
                'updated_by' => 4,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 15,
                'user_id' => 4,
                'profile_id' => 4,
                'entertainment_type' => 'video', 
                'created_by' => 4,
                'updated_by' => 4,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 10,
                'user_id' => 4,
                'profile_id' => 4,
                'entertainment_type' => 'video', 
                'created_by' => 4,
                'updated_by' => 4,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 5,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'video', 
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 65,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'movie', 
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 2,
                'user_id' => 4,
                'profile_id' => 4,
                'entertainment_type' => 'tvshow', 
                'created_by' => 4,
                'updated_by' => 4,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 8,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'video', 
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 18,
                'user_id' => 4,
                'profile_id' => 4,
                'entertainment_type' => 'video', 
                'created_by' => 4,
                'updated_by' => 4,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 18,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'tvshow', 
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 4,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'movie', 
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 6,
                'user_id' => 4,
                'profile_id' => 4,
                'entertainment_type' => 'tvshow', 
                'created_by' => 4,
                'updated_by' => 4,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 1,
                'user_id' => 5,
                'profile_id' => 5,
                'entertainment_type' => 'movie', 
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 8,
                'user_id' => 6,
                'profile_id' => 6,
                'entertainment_type' => 'video', 
                'created_by' => 6,
                'updated_by' => 6,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 10,
                'user_id' => 7,
                'profile_id' => 7,
                'entertainment_type' => 'movie', 
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 17,
                'user_id' => 8,
                'profile_id' => 8,
                'entertainment_type' => 'tvshow', 
                'created_by' => 8,
                'updated_by' => 8,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 9,
                'user_id' => 9,
                'profile_id' => 9,
                'entertainment_type' => 'video', 
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 12,
                'user_id' => 10,
                'profile_id' => 10,
                'entertainment_type' => 'movie', 
                'created_by' => 10,
                'updated_by' => 10,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 20,
                'user_id' => 11,
                'profile_id' => 11,
                'entertainment_type' => 'video', 
                'created_by' => 11,
                'updated_by' => 11,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 30,
                'user_id' => 12,
                'profile_id' => 12,
                'entertainment_type' => 'video', 
                'created_by' => 12,
                'updated_by' => 12,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 31,
                'user_id' => 13,
                'profile_id' => 13,
                'entertainment_type' => 'video', 
                'created_by' => 13,
                'updated_by' => 13,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 32,
                'user_id' => 14,
                'profile_id' => 14,
                'entertainment_type' => 'video', 
                'created_by' => 14,
                'updated_by' => 14,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 33,
                'user_id' => 15,
                'profile_id' => 15,
                'entertainment_type' => 'video', 
                'created_by' => 15,
                'updated_by' => 15,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 34,
                'user_id' => 5,
                'profile_id' => 5,
                'entertainment_type' => 'video', 
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 35,
                'user_id' => 6,
                'profile_id' => 6,
                'entertainment_type' => 'video', 
                'created_by' => 6,
                'updated_by' => 6,
                'deleted_by' => null,
            ],
            [
                'entertainment_id' => 36,
                'user_id' => 7,
                'profile_id' => 7,
                'entertainment_type' => 'video', 
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => null,
            ],

          
        ]);
    }
}
